import type { ColorThemeDefinition, ThemeName } from "../types";

export const THEMES: Record<ThemeName, ColorThemeDefinition> = {
  default: {
    name: "Aether Indigo (Default)",
    description: "Signature dark canvas with vivid indigo strokes and slate fills",
    isDark: true,
    canvasBackground: "#090d16",
    nodeStrokes: ["#6366f1", "#818cf8", "#a5b4fc", "#38bdf8"],
    nodeFills: ["#1e1b4b", "#172554", "#1e293b"],
    arrowColor: "#818cf8",
    textColor: "#f8fafc",
    roughness: 0,
    fillStyle: "solid",
  },
  nord: {
    name: "Nordic Frost",
    description: "Cool arctic palette inspired by the Nord theme",
    isDark: true,
    canvasBackground: "#2e3440",
    nodeStrokes: ["#88c0d0", "#81a1c1", "#5e81ac", "#b48ead"],
    nodeFills: ["#3b4252", "#434c5e", "#4c566a"],
    arrowColor: "#d8dee9",
    textColor: "#eceff4",
    roughness: 0,
    fillStyle: "solid",
  },
  cyberpunk: {
    name: "Cyberpunk Neon",
    description: "High-contrast neon colors against a deep void canvas",
    isDark: true,
    canvasBackground: "#090a10",
    nodeStrokes: ["#ff007f", "#00f0ff", "#ffe600", "#a855f7"],
    nodeFills: ["#1e1028", "#0e2433", "#221133"],
    arrowColor: "#00f0ff",
    textColor: "#ffffff",
    roughness: 0,
    fillStyle: "solid",
  },
  blueprint: {
    name: "Blueprint",
    description: "Architectural blueprint style with sky blue lines on navy",
    isDark: true,
    canvasBackground: "#1e3a5f",
    nodeStrokes: ["#93c5fd", "#60a5fa", "#38bdf8"],
    nodeFills: ["#172554", "#1e3a5f", "#0f2347"],
    arrowColor: "#93c5fd",
    textColor: "#ffffff",
    roughness: 0,
    fillStyle: "hachure",
  },
  minimal_dark: {
    name: "Minimal Dark",
    description: "Sleek and distraction-free dark slate palette",
    isDark: true,
    canvasBackground: "#0f172a",
    nodeStrokes: ["#94a3b8", "#cbd5e1", "#e2e8f0"],
    nodeFills: ["#1e293b", "#334155"],
    arrowColor: "#94a3b8",
    textColor: "#f8fafc",
    roughness: 0,
    fillStyle: "solid",
  },
  solarized: {
    name: "Solarized Dark",
    description: "Warm, precision color palette designed for low eye strain",
    isDark: true,
    canvasBackground: "#002b36",
    nodeStrokes: ["#268bd2", "#2aa198", "#859900", "#b58900", "#cb4b16"],
    nodeFills: ["#073642", "#002b36"],
    arrowColor: "#93a1a1",
    textColor: "#fdf6e3",
    roughness: 0,
    fillStyle: "solid",
  },
  pastel: {
    name: "Pastel Dream (Light)",
    description: "Soft modern pastel tones on clean light canvas",
    isDark: false,
    canvasBackground: "#f8fafc",
    nodeStrokes: ["#6366f1", "#ec4899", "#0d9488", "#eab308"],
    nodeFills: ["#e0e7ff", "#fce7f3", "#ccfbf1", "#fef9c3"],
    arrowColor: "#64748b",
    textColor: "#1e293b",
    roughness: 1,
    fillStyle: "solid",
  },
};

export function getTheme(name?: ThemeName): ColorThemeDefinition {
  if (name && THEMES[name]) {
    return THEMES[name];
  }
  return THEMES.default;
}
